CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT PK__app_users PRIMARY KEY (id),
    CONSTRAINT UQ__app_users_username UNIQUE(username)
);

CREATE TABLE habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    frequency VARCHAR(50) NOT NULL,
    created_at DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    user_id BIGINT NOT NULL,

    CONSTRAINT PK__habits PRIMARY KEY (id),
    CONSTRAINT FK__habits__app_users
        FOREIGN KEY(user_id)
        REFERENCES app_users(id)
        ON DELETE CASCADE
);

CREATE TABLE habit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    points_awarded INTEGER,
    habit_id BIGINT NOT NULL,

    CONSTRAINT PK__habit_logs PRIMARY KEY (id),
    CONSTRAINT FK__habit_logs__habits
                    FOREIGN KEY(habit_id)
                    REFERENCES habits(id)
                    ON DELETE CASCADE
);

CREATE INDEX IDX__habit_logs__habit_id ON habit_logs(habit_id);
CREATE INDEX IDX__habits__user_id ON habits(user_id);
